name: 股票即時通知

on:
  workflow_dispatch:

jobs:
  stock-check:
    runs-on: ubuntu-latest

    steps:
      - name: 下載程式碼
        uses: actions/checkout@v4

      - name: 設定 Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 安裝套件
        run: |
          pip install yfinance requests

      - name: 執行股票程式
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python test1.py
